In [1]:
import seaborn as sns
import numpy as np
import pandas as pd

In [2]:
penguins = sns.load_dataset('penguins')
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [3]:
penguins_biscoe = penguins[(penguins["island"] == "Biscoe") & (penguins["bill_length_mm"] > 48)]
penguins_biscoe.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
221,Gentoo,Biscoe,50.0,16.3,230.0,5700.0,Male
222,Gentoo,Biscoe,48.7,14.1,210.0,4450.0,Female
223,Gentoo,Biscoe,50.0,15.2,218.0,5700.0,Male
231,Gentoo,Biscoe,49.0,16.1,216.0,5550.0,Male
233,Gentoo,Biscoe,48.4,14.6,213.0,5850.0,Male

In [4]:
penguins_adelie = penguins[
    (penguins["species"] == "Adelie")
    & (penguins["sex"] == "Male")
    & (penguins["island"] != "Biscoe")
]
penguins_adelie.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,Male
13,Adelie,Torgersen,38.6,21.2,191.0,3800.0,Male
14,Adelie,Torgersen,34.6,21.1,198.0,4400.0,Male

In [5]:
penguins.drop(["sex", "body_mass_g"], axis=1, inplace=True)

In [6]:
penguins.head()

  species     island  bill_length_mm  bill_depth_mm  flipper_length_mm
0  Adelie  Torgersen            39.1           18.7              181.0
1  Adelie  Torgersen            39.5           17.4              186.0
2  Adelie  Torgersen            40.3           18.0              195.0
3  Adelie  Torgersen             NaN            NaN                NaN
4  Adelie  Torgersen            36.7           19.3              193.0

In [7]:
# 4
penguins = sns.load_dataset('penguins')

In [8]:
penguins = penguins[penguins["island"] != "Biscoe"]

In [9]:
penguins.columns

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='object')

In [10]:
penguins = penguins[['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g']]

In [11]:
penguins = penguins.rename(columns={'species': 'especie_pinguino'})

In [12]:
penguins.groupby('especie_pinguino').size()

especie_pinguino
Adelie       108
Chinstrap     68
dtype: int64

In [13]:
(
    penguins.groupby('especie_pinguino')
        [[c for c in penguins.columns if "length" in c]]
    .mean()
    .rename(columns={c: f"{c}_mean" for c in penguins.columns})
)

                  bill_length_mm_mean  flipper_length_mm_mean
especie_pinguino
Adelie                      38.715888              190.429907
Chinstrap                   48.833824              195.823529

In [14]:
# 5
penguins = sns.load_dataset('penguins')

In [15]:
penguins.rename(columns={'species': 'especies'})

,especies,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [16]:
penguins.rename(
    columns={
        'flipper_length_mm': 'aleta_mm',
        'body_mass_g': 'peso_g'
    }
)

,species,island,bill_length_mm,bill_depth_mm,aleta_mm,peso_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [17]:
penguins.rename(index={0: 'cero'})

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
cero,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [18]:
penguins.rename(columns=str.upper)

,SPECIES,ISLAND,BILL_LENGTH_MM,BILL_DEPTH_MM,FLIPPER_LENGTH_MM,BODY_MASS_G,SEX
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [19]:
# deberia convertir los indices a la raiz cuadrada de cada uno
penguins.rename(index=np.sqrt)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0.000000,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1.000000,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
1.414214,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
1.732051,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
2.000000,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
18.411953,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
18.439089,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
18.466185,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
18.493242,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
18.520259,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [20]:
def suma_uno(x):
    return x+1

In [21]:
penguins.rename(index=suma_uno)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
1,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
2,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
3,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
5,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
340,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
341,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
342,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
343,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
344,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [22]:
# deberia transformar los indices multiplicandolos por 2
penguins.rename(index = lambda x : x * 2)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
2,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
4,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
6,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
8,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
678,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
680,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
682,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
684,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
686,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [23]:
penguins.rename(columns = lambda s : s.upper())

,SPECIES,ISLAND,BILL_LENGTH_MM,BILL_DEPTH_MM,FLIPPER_LENGTH_MM,BODY_MASS_G,SEX
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [24]:
# 6
macro = pd.read_csv('../Notebooks/Datasets-20260209/macro_full_columns.csv')
macro.head()

,Unnamed: 0,Anio,FBKF.Construcciones.Priv_Publ,FBKF.Equi_Dur_Prod.Mat_Transp.Nac,FBKF.Equi_Dur_Prod.Mat_Transp.Import,FBKF.Equi_Dur_Prod.Maqui_YEqui.Nac,FBKF.Equi_Dur_Prod.Maqui_YEqui.Import,Consumo.Hogares,Consumo.Gobierno,Exportaciones,...,PBI_a_precios_de_mercado.oferta,Vol_PIB_perCap,Vol_Consumo_Hogares_Per_Cap,Vol_FBKF_perCap,PIB_perCap__variPorc,Vol_Cons_Hogares_per_Cap__vari_Porc,Vol_FBKF_perCap__variPorc,Vol_PIB_encaden_Fisher_2004,IPI_volumen,IPI__variPorc
0,1,1950,20353627362,6.685869e+08,5.844002e+08,3119383475,8.631124e+08,1.046560e+11,21706316451,1.072959e+10,...,1.420980e+11,8230.718755,6061.927168,1265.389774,NaN,NaN,NaN,1.420980e+11,0.292917,NaN
1,2,1951,21739314091,8.427402e+08,2.532758e+09,3562534310,1.292775e+09,1.105380e+11,21767097618,8.455494e+09,...,1.474360e+11,8360.967138,6268.494407,1442.153759,0.015825,0.034076,0.139691,1.474360e+11,0.303920,0.037563
2,3,1952,19685428171,1.119084e+09,1.484422e+09,3440750327,1.088416e+09,1.051080e+11,21455589059,6.224082e+09,...,1.404910e+11,7806.866125,5840.680245,1293.154332,-0.066272,-0.068248,-0.103317,1.404910e+11,0.289604,-0.047104
3,4,1953,20237375978,1.207891e+09,1.459989e+09,3621895632,8.869267e+08,1.064030e+11,20742065172,9.619869e+09,...,1.473240e+11,8027.665603,5797.868309,1290.488829,0.028283,-0.007330,-0.002061,1.473240e+11,0.303689,0.048637
4,5,1954,19372130307,1.173452e+09,8.059002e+08,4121320340,7.830799e+08,1.143920e+11,21238933697,1.020162e+10,...,1.533160e+11,8196.878491,6115.886428,1230.475866,0.021079,0.054851,-0.046504,1.533160e+11,0.316039,0.040667

In [25]:
macro.isna().sum(axis = 0)

Unnamed: 0                              0
Anio                                    0
FBKF.Construcciones.Priv_Publ           0
FBKF.Equi_Dur_Prod.Mat_Transp.Nac       0
FBKF.Equi_Dur_Prod.Mat_Transp.Import    0
                                       ..
Vol_Cons_Hogares_per_Cap__vari_Porc     1
Vol_FBKF_perCap__variPorc               1
Vol_PIB_encaden_Fisher_2004             0
IPI_volumen                             0
IPI__variPorc                           1
Length: 85, dtype: int64

In [51]:
# Genero una lista de columnas con algun dato faltante
macro_cols_with_nans = macro.columns[macro.isna().any(axis=0)]
macro_cols_with_nans

Index(['EXPO_OTAGRIC_2004', 'EXPO_PESCA_2004', 'EXPO_ALIMENT_2004',
       'EXPO_TEXTIL_2004', 'EXPO_CUEROIND_2004', 'EXPO_PAPEL_2004',
       'EXPO_CAUCHO_2004', 'EXPO_QUIMICO_2004', 'EXPO_COMBIUST_2004',
       'EXPO_HIERRO_2004', 'EXPO_METNOFERR_2004', 'EXPO_MAQUIN_2004',
       'EXPO_RESTOIND_2004', 'PIB_perCap__variPorc',
       'Vol_Cons_Hogares_per_Cap__vari_Porc', 'Vol_FBKF_perCap__variPorc',
       'IPI__variPorc'],
      dtype='object')

In [52]:
# En que años hay datos faltantes? axis=1 mira filas
macro[macro.isna().any(axis=1)]['Anio']

0     1950
1     1951
2     1952
3     1953
4     1954
5     1955
6     1956
7     1957
8     1958
9     1959
10    1960
11    1961
12    1962
13    1963
14    1964
15    1965
Name: Anio, dtype: int64

In [54]:
# Convierto datos faltantes a 0
macro = macro.fillna(0)

In [56]:
macro.isna().any(axis=0).sum()

np.int64(0)

In [29]:
# 7
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [30]:
# Elimino filas con datos faltantes
penguins_sin_na = penguins.dropna()
penguins_sin_na

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [31]:
# Los indices me quedaron "mal" (no consecutivos)
# restablezco indices
penguins_sin_na.reset_index(drop=True)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
4,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
...,...,...,...,...,...,...,...
328,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female
329,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
330,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
331,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
332,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [32]:
# Todo junto, encadenando
(
    penguins
    .dropna()
    .reset_index(drop=True)
)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
4,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
...,...,...,...,...,...,...,...
328,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female
329,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
330,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
331,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
332,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [33]:
# 8
# Salida esperada:
# ['hola!', 'chau!']
[saludo + '!' for saludo in ['hola', 'chau']]

['hola!', 'chau!']

In [34]:
penguins.columns = [c.upper() for c in penguins.columns]
penguins.head()

,SPECIES,ISLAND,BILL_LENGTH_MM,BILL_DEPTH_MM,FLIPPER_LENGTH_MM,BODY_MASS_G,SEX
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [35]:
# 9
penguins = sns.load_dataset('penguins')
penguins.columns = [c.upper() if 'bill' in c else c for c in penguins.columns]
penguins.head()

,species,island,BILL_LENGTH_MM,BILL_DEPTH_MM,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [36]:
# 10
penguins = sns.load_dataset('penguins')
penguins['bin'] = penguins.apply(lambda row: 'chico' if row['body_mass_g'] < 4000 else 'grande', axis=1)
penguins.head(15)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bin
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,chico
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,chico
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,chico
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,grande
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,chico
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,chico
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,Female,chico
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,Male,grande
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN,chico
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN,grande
10,Adelie,Torgersen,37.8,17.1,186.0,3300.0,NaN,chico
11,Adelie,Torgersen,37.8,17.3,180.0,3700.0,NaN,chico
12,Adelie,Torgersen,41.1,17.6,182.0,3200.0,Female,chico
13,Adelie,Torgersen,38.6,21.2,191.0,3800.0,Male,chico
14,Adelie,Torgersen,34.6,21.1,198.0,4400.0,Male,grande

In [37]:
# 11
columns_mm = [col for col in penguins.columns if col.endswith('_mm')]
penguins[(penguins['flipper_length_mm'] > 200) & (penguins['sex'] == 'Male')][columns_mm]

     bill_length_mm  bill_depth_mm  flipper_length_mm
91             41.1           18.1              205.0
95             40.8           18.9              208.0
101            41.0           20.0              203.0
123            41.4           18.5              202.0
129            44.1           18.0              210.0
..              ...            ...                ...
333            51.5           16.3              230.0
335            55.1           16.0              230.0
337            48.8           16.2              222.0
341            50.4           15.7              222.0
343            49.9           16.1              213.0

[84 rows x 3 columns]

In [38]:
# 12
penguins = sns.load_dataset('penguins')
cols = [c for c in penguins.columns if c.startswith('bill') or c == "species"]
penguins[penguins["island"] == "Dream"][cols]

       species  bill_length_mm  bill_depth_mm
30      Adelie            39.5           16.7
31      Adelie            37.2           18.1
32      Adelie            39.5           17.8
33      Adelie            40.9           18.9
34      Adelie            36.4           17.0
..         ...             ...            ...
215  Chinstrap            55.8           19.8
216  Chinstrap            43.5           18.1
217  Chinstrap            49.6           18.2
218  Chinstrap            50.8           19.0
219  Chinstrap            50.2           18.7

[124 rows x 3 columns]

In [39]:
# 13
penguins['body_mass_kg'] = penguins['body_mass_g'] / 1000
penguins_new = penguins.rename(columns = {'island': 'ISLAND'})
penguins_new.head()

,species,ISLAND,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,body_mass_kg
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,3.75
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,3.80
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,3.25
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,3.45

In [40]:
# 14
s = penguins.groupby('species')['body_mass_g'].agg('median')
s

species
Adelie       3700.0
Chinstrap    3700.0
Gentoo       5000.0
Name: body_mass_g, dtype: float64

In [41]:
penguins['mediana_masa_corporal'] = [s[x] for x in penguins['species']]
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,body_mass_kg,mediana_masa_corporal
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,3.75,3700.0
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,3.80,3700.0
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,3.25,3700.0
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,NaN,3700.0
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,3.45,3700.0
...,...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,NaN,5000.0
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,4.85,5000.0
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,5.75,5000.0
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,5.20,5000.0
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,5.40,5000.0

In [42]:
# 15
penguins = sns.load_dataset('penguins')
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [43]:
cols = [c for c in penguins.columns if c != 'sex']
cols_length = [c for c in penguins.columns if 'length' in c]

(
    penguins[penguins['island'] != "Biscoe"][cols]
    .rename(columns={'species': 'especie_pinguino'})
    .groupby('especie_pinguino')[cols_length]
    .agg('mean')
    .rename(columns = lambda x: x + '_mean')
)

                  bill_length_mm_mean  flipper_length_mm_mean
especie_pinguino
Adelie                      38.715888              190.429907
Chinstrap                   48.833824              195.823529

In [44]:
# 16
macroFull = pd.read_csv("../Notebooks/Datasets-20260209/macro_full_columns.csv", index_col = "Anio")
macroFull.head()

,Unnamed: 0,FBKF.Construcciones.Priv_Publ,FBKF.Equi_Dur_Prod.Mat_Transp.Nac,FBKF.Equi_Dur_Prod.Mat_Transp.Import,FBKF.Equi_Dur_Prod.Maqui_YEqui.Nac,FBKF.Equi_Dur_Prod.Maqui_YEqui.Import,Consumo.Hogares,Consumo.Gobierno,Exportaciones,Importaciones,...,PBI_a_precios_de_mercado.oferta,Vol_PIB_perCap,Vol_Consumo_Hogares_Per_Cap,Vol_FBKF_perCap,PIB_perCap__variPorc,Vol_Cons_Hogares_per_Cap__vari_Porc,Vol_FBKF_perCap__variPorc,Vol_PIB_encaden_Fisher_2004,IPI_volumen,IPI__variPorc
Anio,,,,,,,,,,,,,,,,,,,,,
1950,1,20353627362,6.685869e+08,5.844002e+08,3119383475,8.631124e+08,1.046560e+11,21706316451,1.072959e+10,1.403947e+10,...,1.420980e+11,8230.718755,6061.927168,1265.389774,NaN,NaN,NaN,1.420980e+11,0.292917,NaN
1951,2,21739314091,8.427402e+08,2.532758e+09,3562534310,1.292775e+09,1.105380e+11,21767097618,8.455494e+09,1.574444e+10,...,1.474360e+11,8360.967138,6268.494407,1442.153759,0.015825,0.034076,0.139691,1.474360e+11,0.303920,0.037563
1952,3,19685428171,1.119084e+09,1.484422e+09,3440750327,1.088416e+09,1.051080e+11,21455589059,6.224082e+09,1.163759e+10,...,1.404910e+11,7806.866125,5840.680245,1293.154332,-0.066272,-0.068248,-0.103317,1.404910e+11,0.289604,-0.047104
1953,4,20237375978,1.207891e+09,1.459989e+09,3621895632,8.869267e+08,1.064030e+11,20742065172,9.619869e+09,9.626751e+09,...,1.473240e+11,8027.665603,5797.868309,1290.488829,0.028283,-0.007330,-0.002061,1.473240e+11,0.303689,0.048637
1954,5,19372130307,1.173452e+09,8.059002e+08,4121320340,7.830799e+08,1.143920e+11,21238933697,1.020162e+10,1.250629e+10,...,1.533160e+11,8196.878491,6115.886428,1230.475866,0.021079,0.054851,-0.046504,1.533160e+11,0.316039,0.040667

In [45]:
macroFull.columns

Index(['Unnamed: 0', 'FBKF.Construcciones.Priv_Publ',
       'FBKF.Equi_Dur_Prod.Mat_Transp.Nac',
       'FBKF.Equi_Dur_Prod.Mat_Transp.Import',
       'FBKF.Equi_Dur_Prod.Maqui_YEqui.Nac',
       'FBKF.Equi_Dur_Prod.Maqui_YEqui.Import', 'Consumo.Hogares',
       'Consumo.Gobierno', 'Exportaciones', 'Importaciones', 'GIB', 'FKBF',
       'EXPO_TOT_2004', 'EXPO_AGROP_2004', 'EXPO_PAMP_2004',
       'EXPO_PECUAR_2004', 'EXPO_CARNES_2004', 'EXPO_LECHE_2004',
       'EXPO_LANAS_2004', 'EXPO_CUEROS_PP_2004', 'EXPO_AGRIC_2004',
       'EXPO_CEREAL_2004', 'EXPO_OLEAGI_2004', 'EXPO_OTAGRIC_2004',
       'EXPO_PESCA_2004', 'EXPO_INDUST_2004', 'EXPO_ALIMENT_2004',
       'EXPO_TEXTIL_2004', 'EXPO_CUEROIND_2004', 'EXPO_PAPEL_2004',
       'EXPO_CAUCHO_2004', 'EXPO_QUIMICO_2004', 'EXPO_COMBIUST_2004',
       'EXPO_HIERRO_2004', 'EXPO_METNOFERR_2004', 'EXPO_MAQUIN_2004',
       'EXPO_RESTOIND_2004', 'Consumo.Hogares.ipi.demanda',
       'Consumo.Gobierno.ipi.demanda',
       'FBKF.Construcciones.Priv_Publ.ipi.demanda',
       'FBKF.Equi_Dur_Prod.Mat_Transp.Nac.ipi.demanda',
       'FBKF.Equi_Dur_Prod.Mat_Transp.Import.ipi.demanda',
       'FBKF.Equi_Dur_Prod.Maqui_YEqui.Nac.ipi.demanda',
       'FBKF.Equi_Dur_Prod.Maqui_YEqui.Import.ipi.demanda',
       'Exportaciones.ipi.demanda', 'Importaciones.ipi.demanda',
       'GIB.ipi.demanda', 'FBKF.Construcciones.Priv_Publ.ipi.inversion',
       'FBKF.Equi_Dur_Prod.Mat_Transp.Nac.ipi.inversion',
       'FBKF.Equi_Dur_Prod.Mat_Transp.Import.ipi.inversion',
       'FBKF.Equi_Dur_Prod.Maqui_YEqui.Nac.ipi.inversion',
       'FBKF.Equi_Dur_Prod.Maqui_YEqui.Import.ipi.inversion',
       'FKBF.ipi.inversion', 'Agricultura_caza_silvicultura_y_pesca',
       'Explotacion_de_minas_y_canteras', 'Industria_manufacturera',
       'Electricidad_gas_y_agua', 'Construccion',
       'Comercio_hoteles_y_restaurantes', 'Transp_Almac_y_Comunics',
       'Inter_Fin_Seg_Activ_Inmo_Serv_Empr_etc',
       'Servs_Socs_Comunales_Y_Personales', 'Impuesto_Prod_Netos_De_Subsid',
       'PBI_a_precios_de_mercado',
       'Agricultura_caza_silvicultura_y_pesca.oferta',
       'Explotacion_de_minas_y_canteras.oferta',
       'Industria_manufacturera.oferta', 'Electricidad_gas_y_agua.oferta',
       'Construccion.oferta', 'Comercio_hoteles_y_restaurantes.oferta',
       'Transp_Almac_y_Comunics.oferta',
       'Inter_Fin_Seg_Activ_Inmo_Serv_Empr_etc.oferta',
       'Servs_Socs_Comunales_Y_Personales.oferta',
       'Impuesto_Prod_Netos_De_Subsid.oferta',
       'PBI_a_precios_de_mercado.oferta', 'Vol_PIB_perCap',
       'Vol_Consumo_Hogares_Per_Cap', 'Vol_FBKF_perCap',
       'PIB_perCap__variPorc', 'Vol_Cons_Hogares_per_Cap__vari_Porc',
       'Vol_FBKF_perCap__variPorc', 'Vol_PIB_encaden_Fisher_2004',
       'IPI_volumen', 'IPI__variPorc'],
      dtype='object')

In [46]:
macroFull = macroFull.drop("Unnamed: 0", axis=1)

In [47]:
macroFull.head()

,FBKF.Construcciones.Priv_Publ,FBKF.Equi_Dur_Prod.Mat_Transp.Nac,FBKF.Equi_Dur_Prod.Mat_Transp.Import,FBKF.Equi_Dur_Prod.Maqui_YEqui.Nac,FBKF.Equi_Dur_Prod.Maqui_YEqui.Import,Consumo.Hogares,Consumo.Gobierno,Exportaciones,Importaciones,GIB,...,PBI_a_precios_de_mercado.oferta,Vol_PIB_perCap,Vol_Consumo_Hogares_Per_Cap,Vol_FBKF_perCap,PIB_perCap__variPorc,Vol_Cons_Hogares_per_Cap__vari_Porc,Vol_FBKF_perCap__variPorc,Vol_PIB_encaden_Fisher_2004,IPI_volumen,IPI__variPorc
Anio,,,,,,,,,,,,,,,,,,,,,
1950,20353627362,6.685869e+08,5.844002e+08,3119383475,8.631124e+08,1.046560e+11,21706316451,1.072959e+10,1.403947e+10,1.420980e+11,...,1.420980e+11,8230.718755,6061.927168,1265.389774,NaN,NaN,NaN,1.420980e+11,0.292917,NaN
1951,21739314091,8.427402e+08,2.532758e+09,3562534310,1.292775e+09,1.105380e+11,21767097618,8.455494e+09,1.574444e+10,1.474360e+11,...,1.474360e+11,8360.967138,6268.494407,1442.153759,0.015825,0.034076,0.139691,1.474360e+11,0.303920,0.037563
1952,19685428171,1.119084e+09,1.484422e+09,3440750327,1.088416e+09,1.051080e+11,21455589059,6.224082e+09,1.163759e+10,1.404910e+11,...,1.404910e+11,7806.866125,5840.680245,1293.154332,-0.066272,-0.068248,-0.103317,1.404910e+11,0.289604,-0.047104
1953,20237375978,1.207891e+09,1.459989e+09,3621895632,8.869267e+08,1.064030e+11,20742065172,9.619869e+09,9.626751e+09,1.473240e+11,...,1.473240e+11,8027.665603,5797.868309,1290.488829,0.028283,-0.007330,-0.002061,1.473240e+11,0.303689,0.048637
1954,19372130307,1.173452e+09,8.059002e+08,4121320340,7.830799e+08,1.143920e+11,21238933697,1.020162e+10,1.250629e+10,1.533160e+11,...,1.533160e+11,8196.878491,6115.886428,1230.475866,0.021079,0.054851,-0.046504,1.533160e+11,0.316039,0.040667

In [48]:
macroFull = macroFull.rename(columns = lambda c: c.replace('vari_Porc', 'variPorc'))
macroFull.head()

,FBKF.Construcciones.Priv_Publ,FBKF.Equi_Dur_Prod.Mat_Transp.Nac,FBKF.Equi_Dur_Prod.Mat_Transp.Import,FBKF.Equi_Dur_Prod.Maqui_YEqui.Nac,FBKF.Equi_Dur_Prod.Maqui_YEqui.Import,Consumo.Hogares,Consumo.Gobierno,Exportaciones,Importaciones,GIB,...,PBI_a_precios_de_mercado.oferta,Vol_PIB_perCap,Vol_Consumo_Hogares_Per_Cap,Vol_FBKF_perCap,PIB_perCap__variPorc,Vol_Cons_Hogares_per_Cap__variPorc,Vol_FBKF_perCap__variPorc,Vol_PIB_encaden_Fisher_2004,IPI_volumen,IPI__variPorc
Anio,,,,,,,,,,,,,,,,,,,,,
1950,20353627362,6.685869e+08,5.844002e+08,3119383475,8.631124e+08,1.046560e+11,21706316451,1.072959e+10,1.403947e+10,1.420980e+11,...,1.420980e+11,8230.718755,6061.927168,1265.389774,NaN,NaN,NaN,1.420980e+11,0.292917,NaN
1951,21739314091,8.427402e+08,2.532758e+09,3562534310,1.292775e+09,1.105380e+11,21767097618,8.455494e+09,1.574444e+10,1.474360e+11,...,1.474360e+11,8360.967138,6268.494407,1442.153759,0.015825,0.034076,0.139691,1.474360e+11,0.303920,0.037563
1952,19685428171,1.119084e+09,1.484422e+09,3440750327,1.088416e+09,1.051080e+11,21455589059,6.224082e+09,1.163759e+10,1.404910e+11,...,1.404910e+11,7806.866125,5840.680245,1293.154332,-0.066272,-0.068248,-0.103317,1.404910e+11,0.289604,-0.047104
1953,20237375978,1.207891e+09,1.459989e+09,3621895632,8.869267e+08,1.064030e+11,20742065172,9.619869e+09,9.626751e+09,1.473240e+11,...,1.473240e+11,8027.665603,5797.868309,1290.488829,0.028283,-0.007330,-0.002061,1.473240e+11,0.303689,0.048637
1954,19372130307,1.173452e+09,8.059002e+08,4121320340,7.830799e+08,1.143920e+11,21238933697,1.020162e+10,1.250629e+10,1.533160e+11,...,1.533160e+11,8196.878491,6115.886428,1230.475866,0.021079,0.054851,-0.046504,1.533160e+11,0.316039,0.040667

In [49]:
macroFull = macroFull.rename(columns = lambda c: c.replace('_Per_Cap', '_perCap'))
macroFull.head()

,FBKF.Construcciones.Priv_Publ,FBKF.Equi_Dur_Prod.Mat_Transp.Nac,FBKF.Equi_Dur_Prod.Mat_Transp.Import,FBKF.Equi_Dur_Prod.Maqui_YEqui.Nac,FBKF.Equi_Dur_Prod.Maqui_YEqui.Import,Consumo.Hogares,Consumo.Gobierno,Exportaciones,Importaciones,GIB,...,PBI_a_precios_de_mercado.oferta,Vol_PIB_perCap,Vol_Consumo_Hogares_perCap,Vol_FBKF_perCap,PIB_perCap__variPorc,Vol_Cons_Hogares_per_Cap__variPorc,Vol_FBKF_perCap__variPorc,Vol_PIB_encaden_Fisher_2004,IPI_volumen,IPI__variPorc
Anio,,,,,,,,,,,,,,,,,,,,,
1950,20353627362,6.685869e+08,5.844002e+08,3119383475,8.631124e+08,1.046560e+11,21706316451,1.072959e+10,1.403947e+10,1.420980e+11,...,1.420980e+11,8230.718755,6061.927168,1265.389774,NaN,NaN,NaN,1.420980e+11,0.292917,NaN
1951,21739314091,8.427402e+08,2.532758e+09,3562534310,1.292775e+09,1.105380e+11,21767097618,8.455494e+09,1.574444e+10,1.474360e+11,...,1.474360e+11,8360.967138,6268.494407,1442.153759,0.015825,0.034076,0.139691,1.474360e+11,0.303920,0.037563
1952,19685428171,1.119084e+09,1.484422e+09,3440750327,1.088416e+09,1.051080e+11,21455589059,6.224082e+09,1.163759e+10,1.404910e+11,...,1.404910e+11,7806.866125,5840.680245,1293.154332,-0.066272,-0.068248,-0.103317,1.404910e+11,0.289604,-0.047104
1953,20237375978,1.207891e+09,1.459989e+09,3621895632,8.869267e+08,1.064030e+11,20742065172,9.619869e+09,9.626751e+09,1.473240e+11,...,1.473240e+11,8027.665603,5797.868309,1290.488829,0.028283,-0.007330,-0.002061,1.473240e+11,0.303689,0.048637
1954,19372130307,1.173452e+09,8.059002e+08,4121320340,7.830799e+08,1.143920e+11,21238933697,1.020162e+10,1.250629e+10,1.533160e+11,...,1.533160e+11,8196.878491,6115.886428,1230.475866,0.021079,0.054851,-0.046504,1.533160e+11,0.316039,0.040667