In [1]:
import seaborn as sns
from sklearn.model_selection import KFold
import matplotlib.pyplot as plt

from scipy import stats
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from formulaic import model_matrix

In [ ]:
#import os
#print(pwd)
#os.chdir('./notebooks')

En Python, las funciones y paquetes para trabajar con datos no están pensadas para poder hacerlas "sin saber nada de Python". Al contrario, muchas operaciones sencillas de DataFrames requieren conocer técnicas de programación en Python. Vamos a ver algunas en esta clase, principalmente estas:

## 1. Funciones lambda
## 2. Definición de listas por comprensión

**Ejercicio 1 (repaso).** En el dataset de vinos:
1. renombrar la columna "od280/od315_of_diluted_wines" a "od280_od315_of_diluted_wines".
2. pasar todos los nombres de columnas a mayúsculas

In [2]:
from sklearn.datasets import load_wine
wine = load_wine(as_frame=True)
wineData = wine.data
wineData.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

Hay esencialmente dos formas de renombrar columnas:
1. Utilizar rename()
2. Modificar la lista de nombres de columnas dataframe.columns

Comenzamos con rename().

In [ ]:
wineData.rename??

# O help(pd.DataFrame.rename)

Vemos que podemos renombrar columnas utilizando `columns: dict-like or function`

Para renombrar una columna, usamos rename(columns = _DICT_) y un diccionario con "nombre viejo" como claves y "nombre nuevo" como valores.

In [3]:
wineData.rename(columns = {"od280/od315_of_diluted_wines" : "od280_od315_of_diluted_wines"})

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280_od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

También podemos usar funciones para renombrar columnas.

Para pasar todos los nombres de columnas a mayúsculas, usamos la función str.upper()

In [4]:
wineData.rename(columns = str.upper)

,ALCOHOL,MALIC_ACID,ASH,ALCALINITY_OF_ASH,MAGNESIUM,TOTAL_PHENOLS,FLAVANOIDS,NONFLAVANOID_PHENOLS,PROANTHOCYANINS,COLOR_INTENSITY,HUE,OD280/OD315_OF_DILUTED_WINES,PROLINE
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

Cuando no existe una función que hace exactamente lo que queremos, podemos definirla nosotros.

**Ejemplo:** Agregar a todos los nombres de columnas, el prefijo "orig_".

In [5]:
def agregarPrefijo(s):
    return ("orig_" + s)

agregarPrefijo("edad")

'orig_edad'

In [6]:
wineData.rename(columns = agregarPrefijo)

,orig_alcohol,orig_malic_acid,orig_ash,orig_alcalinity_of_ash,orig_magnesium,orig_total_phenols,orig_flavanoids,orig_nonflavanoid_phenols,orig_proanthocyanins,orig_color_intensity,orig_hue,orig_od280/od315_of_diluted_wines,orig_proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

## 1. Funciones lambda
Resulta engorroso definir una función para usarla solamente dentro del rename. 

Las funciones lambda nos permiten definir funciones anónimas "al vuelo".

La sintaxis es

lambda argumentos : expresion

In [7]:
# Ejemplo
x = lambda a : a + 10
print(x(5))

15

**Nota:** `lambda` es una palabra de python, no es un nombre que elegimos nosotros para la función. Son funciones anónimas (que en este ejemplo la guardamos en la variable x)

In [8]:
# Ejemplo
x = lambda a : a + 1
print(x(5))

6

In [9]:
# Ejemplo (función con dos argumentos o parámetros)
x = lambda a, b : a * b
print(x(5, 6))

30

**Ejercicio:** Como podemos usar una función lambda sin asignarla primero a una variable?

In [ ]:
# Ahora hacemos el rename usando funciones lambda

In [10]:
wineData.rename(columns = lambda x : "orig_" + x)

,orig_alcohol,orig_malic_acid,orig_ash,orig_alcalinity_of_ash,orig_magnesium,orig_total_phenols,orig_flavanoids,orig_nonflavanoid_phenols,orig_proanthocyanins,orig_color_intensity,orig_hue,orig_od280/od315_of_diluted_wines,orig_proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

También podemos usar `rename` para modificar los índices.

**Ejercicio:**
En la base de datos de pingüinos,
1. Cambiar el índice 0 a "Cero".
2. Tomas la raíz cuadradada de los índices (del dataset original).

In [11]:
penguins = sns.load_dataset("penguins")
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [12]:
# Cambiamos el indice 0 a "Cero"
penguins.rename(index={0: 'Cero'})

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
Cero,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [13]:
# Tomamos raiz cuadradas de los índices
penguins.rename(index = np.sqrt)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0.000000,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1.000000,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
1.414214,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
1.732051,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
2.000000,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
18.411953,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
18.439089,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
18.466185,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
18.493242,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
18.520259,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

**Ejemplo:** Si queremos sumarle uno a todos los índices, ¿cómo podemos hacerlo?

In [15]:
# Una posibilidad es modificar el array de índices
penguins.index = penguins.index + 1
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
1,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
2,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
3,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
5,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
340,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
341,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
342,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
343,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
344,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [16]:
# O más brevemente
penguins.index += 1

¿Qué hacemos si queremos primero eliminar filas con datos faltantes, luego resetear los índices y luego sumarle uno a todos los índices?

¿Podemos encadenar esta última operación con las anteriores?

In [17]:
# Para encadenar esa operación podemos usar rename y una función lambda!
penguins.rename(index = lambda a : a + 1)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
3,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
4,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
5,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
6,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
7,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
342,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
343,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
344,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
345,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
346,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

Esta operación la podemos encadenar con las anteriores:

In [18]:
penguinsClean = penguins.dropna().reset_index(drop = True).rename(index = lambda a : a + 1)
penguinsClean.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
1,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
2,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
3,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male

In [19]:
# O si queremos cada metodo en una linea nueva
penguinsClean = (
    penguins.dropna()
    .reset_index(drop = True)
    .rename(index = lambda a : a + 1)
)
penguinsClean.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
1,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
2,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
3,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male

**Ejercicio:** Encadanar un método más para cambiar todos los _ por -.

## 2. Listas por comprensión

**Ejemplo:** Queremos cargar el siguiente dataset de variables de oferta y demanda nacional y generar un nuevo dataset que contenga sólo las variables de oferta (las que comienzan con "Oferta").

¿Cómo podemos hacerlo?

In [22]:
macro = pd.read_csv("OfertaYDemanda.csv")
macro.head()

,ano,pbi,OfertaAgricultura,OfertaMinas,OfertaManufacturera,OfertaElectricidad,OfertaConstruccion,OfertaComercio,OfertaTransporte,OfertaFinaciera,...,DemandaConsumoHogares,DemandaConsumoGobiertano,DemandaConstrucciones,DemandaMaterialNacional,DemandaMaterialImportada,DemandaMaquinariaNacional,DemandaMaquinariaImportaciones,DemandaExportaciones,DemandaImportaciones,DemandaGib
0,1950,142098481044,13696637358,1452011417,32304751942,198218385,5918090281,25281650565,7262970408,19550757718,...,104655579712,21706316451,20353627362,668586865,584400198,3119383475,863112352,10729585056,14039465296,142098481044
1,1951,147436076837,14629457210,1686941522,33149279696,212725994,6060937395,26260862055,7534071597,19902737804,...,110537717447,21767097618,21739314091,842740200,2532757698,3562534310,1292775007,8455493993,15744444593,147436076837
2,1952,140491256038,12545616104,1794762161,32522906863,227896262,5571363747,24417324287,7017131008,20598804008,...,105108053681,21455589059,19685428171,1119084065,1484421674,3440750327,1088415946,6224082425,11637586183,140491256038
3,1953,147324304004,16402296333,1925706862,32341045582,242404261,5546340195,24009746257,7210541490,20716225895,...,106402901621,20742065172,20237375978,1207890913,1459988875,3621895632,886926720,9619869463,9626750804,147324304004
4,1954,153315563451,16308747029,2037374129,34903529762,263839496,5308705373,25492912808,7558082163,21278479393,...,114392396415,21238933697,19372130307,1173451578,805900196,4121320340,783079947,10201623290,12506287869,153315563451

In [23]:
macro.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ano                             66 non-null     int64
 1   pbi                             66 non-null     int64
 2   OfertaAgricultura               66 non-null     int64
 3   OfertaMinas                     66 non-null     int64
 4   OfertaManufacturera             66 non-null     int64
 5   OfertaElectricidad              66 non-null     int64
 6   OfertaConstruccion              66 non-null     int64
 7   OfertaComercio                  66 non-null     int64
 8   OfertaTransporte                66 non-null     int64
 9   OfertaFinaciera                 66 non-null     int64
 10  OfertaSociales                  66 non-null     int64
 11  OfertaImpuestos                 66 non-null     int64
 12  DemandaConsumoHogares           66 non-null     int64
 13  DemandaConsumoGobiertano        66 non-null     int64
 14  DemandaConstrucciones           66 non-null     int64
 15  DemandaMaterialNacional         66 non-null     int64
 16  DemandaMaterialImportada        66 non-null     int64
 17  DemandaMaquinariaNacional       66 non-null     int64
 18  DemandaMaquinariaImportaciones  66 non-null     int64
 19  DemandaExportaciones            66 non-null     int64
 20  DemandaImportaciones            66 non-null     int64
 21  DemandaGib                      66 non-null     int64
dtypes: int64(22)
memory usage: 11.5 KB

Para quedarnos con algunas columnas no necesitamos ningún comando especial, solo pasarle la lista de columnas que queremos.

In [25]:
# Ejemplo. Si queremos solo las variables ano y pbi...
macro[["ano", "pbi"]]

     ano           pbi
0   1950  142098481044
1   1951  147436076837
2   1952  140491256038
3   1953  147324304004
4   1954  153315563451
..   ...           ...
61  2011  711876372894
62  2012  706420870168
63  2013  722040183987
64  2014  705611747648
65  2015  722561538316

[66 rows x 2 columns]

¿Cómo generamos una lista con las columnas que comienzan con "Oferta"?

In [26]:
# De esta lista queremos quedarnos con las variables de oferta
macro.columns

Index(['ano', 'pbi', 'OfertaAgricultura', 'OfertaMinas', 'OfertaManufacturera',
       'OfertaElectricidad', 'OfertaConstruccion', 'OfertaComercio',
       'OfertaTransporte', 'OfertaFinaciera', 'OfertaSociales',
       'OfertaImpuestos', 'DemandaConsumoHogares', 'DemandaConsumoGobiertano',
       'DemandaConstrucciones', 'DemandaMaterialNacional',
       'DemandaMaterialImportada', 'DemandaMaquinariaNacional',
       'DemandaMaquinariaImportaciones', 'DemandaExportaciones',
       'DemandaImportaciones', 'DemandaGib'],
      dtype='object')

Definimos **listas por comprensión**.

### A. Sintaxis básica

`[f(x) for x in LISTA]`

In [27]:
# Ejemplo
[x + 1 for x in [2, 3, 5]]

[3, 4, 6]

In [28]:
# Ejemplo
# Si queremos agregarle _orig a todas las variables
[x+'_orig' for x in macro.columns]

['ano_orig',
 'pbi_orig',
 'OfertaAgricultura_orig',
 'OfertaMinas_orig',
 'OfertaManufacturera_orig',
 'OfertaElectricidad_orig',
 'OfertaConstruccion_orig',
 'OfertaComercio_orig',
 'OfertaTransporte_orig',
 'OfertaFinaciera_orig',
 'OfertaSociales_orig',
 'OfertaImpuestos_orig',
 'DemandaConsumoHogares_orig',
 'DemandaConsumoGobiertano_orig',
 'DemandaConstrucciones_orig',
 'DemandaMaterialNacional_orig',
 'DemandaMaterialImportada_orig',
 'DemandaMaquinariaNacional_orig',
 'DemandaMaquinariaImportaciones_orig',
 'DemandaExportaciones_orig',
 'DemandaImportaciones_orig',
 'DemandaGib_orig']

In [29]:
# Que hace este comando?
[col[:2] for col in macro.columns] # devuelve la lista de columnas con solo los 2 primeros caracteres

# Recordar que un string es una sequencia de caracteres.

['an',
 'pb',
 'Of',
 'Of',
 'Of',
 'Of',
 'Of',
 'Of',
 'Of',
 'Of',
 'Of',
 'Of',
 'De',
 'De',
 'De',
 'De',
 'De',
 'De',
 'De',
 'De',
 'De',
 'De']

**Ejercicio:** Convertir todos los nombres de columnas del DataFrame macro a mayúsculas usando listas por comprensión.

In [30]:
[c.upper() for c in macro.columns]

['ANO',
 'PBI',
 'OFERTAAGRICULTURA',
 'OFERTAMINAS',
 'OFERTAMANUFACTURERA',
 'OFERTAELECTRICIDAD',
 'OFERTACONSTRUCCION',
 'OFERTACOMERCIO',
 'OFERTATRANSPORTE',
 'OFERTAFINACIERA',
 'OFERTASOCIALES',
 'OFERTAIMPUESTOS',
 'DEMANDACONSUMOHOGARES',
 'DEMANDACONSUMOGOBIERTANO',
 'DEMANDACONSTRUCCIONES',
 'DEMANDAMATERIALNACIONAL',
 'DEMANDAMATERIALIMPORTADA',
 'DEMANDAMAQUINARIANACIONAL',
 'DEMANDAMAQUINARIAIMPORTACIONES',
 'DEMANDAEXPORTACIONES',
 'DEMANDAIMPORTACIONES',
 'DEMANDAGIB']

In [31]:
# Ejemplo. Esto funcionará?
[np.sqrt(x) for x**2 in np.arange(1,10)]

SyntaxError: cannot assign to expression (2404129098.py, line 2)

### B. Seleccionar solo los valores que cumplen una condición.

En este caso usamos la sintaxis

`[x for x in LISTA if CONDICION]`

In [32]:
# Ejemplo
[x for x in ["hola", "saludos", "chau"] if len(x) == 4]

['hola', 'chau']

In [33]:
# Ejemplo
[x for x in np.arange(1,10) if x % 2 == 0]   # np.arange nos da todos los enteros desde 1 a 10 (exclusive)

[np.int64(2), np.int64(4), np.int64(6), np.int64(8)]

In [34]:
# Ejemplo
# Podemos también aplicar una función a los valores que cumplen la condición
[x**2 for x in np.arange(1,10) if x % 2 == 0]   # np.arange nos da todos los enteros desde 1 a 10 (exclusive)

[np.int64(4), np.int64(16), np.int64(36), np.int64(64)]

**Ejercicio:**
Generar una lista con todas los nombres de variables que comienzan con "Oferta".

In [36]:
cols_oferta = [c for c in macro.columns if c.startswith("Oferta")]
cols_oferta

['OfertaAgricultura',
 'OfertaMinas',
 'OfertaManufacturera',
 'OfertaElectricidad',
 'OfertaConstruccion',
 'OfertaComercio',
 'OfertaTransporte',
 'OfertaFinaciera',
 'OfertaSociales',
 'OfertaImpuestos']

**Ejercicio:**
Generar un DataFrame que contenga solo las variables de Oferta.

In [37]:
macro[cols_oferta]

,OfertaAgricultura,OfertaMinas,OfertaManufacturera,OfertaElectricidad,OfertaConstruccion,OfertaComercio,OfertaTransporte,OfertaFinaciera,OfertaSociales,OfertaImpuestos
0,13696637358,1452011417,32304751942,198218385,5918090281,25281650565,7262970408,19550757718,21743658464,14697709118
1,14629457210,1686941522,33149279696,212725994,6060937395,26260862055,7534071597,19902737804,22368440435,15394949124
2,12545616104,1794762161,32522906863,227896262,5571363747,24417324287,7017131008,20598804008,22577377299,14648699492
3,16402296333,1925706862,32341045582,242404261,5546340195,24009746257,7210541490,20716225895,23072219963,15257871308
4,16308747029,2037374129,34903529762,263839496,5308705373,25492912808,7558082163,21278479393,23797814592,16078311792
...,...,...,...,...,...,...,...,...,...,...
61,51232247600,23624757639,132833552973,11137192032,22917469985,109669382185,52052730045,98166614131,93837237783,118208323319
62,44579958519,23338178766,128887568646,11655890977,22357980999,107013302114,52391956399,99767726112,97055804064,119116971045
63,49721752068,22404030031,130944551380,11717769879,22344881459,109388604371,53702369755,100256426891,98923181463,123021130374
64,51321551605,22736711813,124263314517,11939156363,21877578423,102335931469,54087653912,98874388852,100532401097,115972956704
65,54675970819,23375961951,124566831310,12346924852,22521998699,104976597217,55417987930,100687552693,103292786749,118778641731

Podemos hacerlo también con `.startswith()`

In [38]:
macroOferta = macro[[col for col in macro.columns if col.startswith("Oferta")]]
macroOferta.head()

,OfertaAgricultura,OfertaMinas,OfertaManufacturera,OfertaElectricidad,OfertaConstruccion,OfertaComercio,OfertaTransporte,OfertaFinaciera,OfertaSociales,OfertaImpuestos
0,13696637358,1452011417,32304751942,198218385,5918090281,25281650565,7262970408,19550757718,21743658464,14697709118
1,14629457210,1686941522,33149279696,212725994,6060937395,26260862055,7534071597,19902737804,22368440435,15394949124
2,12545616104,1794762161,32522906863,227896262,5571363747,24417324287,7017131008,20598804008,22577377299,14648699492
3,16402296333,1925706862,32341045582,242404261,5546340195,24009746257,7210541490,20716225895,23072219963,15257871308
4,16308747029,2037374129,34903529762,263839496,5308705373,25492912808,7558082163,21278479393,23797814592,16078311792

**Ejercicio:** Al DataFrame de Oferta agregar una columna OfertaAgregada que contenga la suma total de la oferta.

In [41]:
macroOferta["OfertaAgregada"] = macroOferta.sum(axis=1)
macroOferta.head()

/tmp/ipykernel_9079/2613782419.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  macroOferta["OfertaAgregada"] = macroOferta.sum(axis=1)

,OfertaAgricultura,OfertaMinas,OfertaManufacturera,OfertaElectricidad,OfertaConstruccion,OfertaComercio,OfertaTransporte,OfertaFinaciera,OfertaSociales,OfertaImpuestos,OfertaAgregada
0,13696637358,1452011417,32304751942,198218385,5918090281,25281650565,7262970408,19550757718,21743658464,14697709118,1.421065e+11
1,14629457210,1686941522,33149279696,212725994,6060937395,26260862055,7534071597,19902737804,22368440435,15394949124,1.472004e+11
2,12545616104,1794762161,32522906863,227896262,5571363747,24417324287,7017131008,20598804008,22577377299,14648699492,1.419219e+11
3,16402296333,1925706862,32341045582,242404261,5546340195,24009746257,7210541490,20716225895,23072219963,15257871308,1.467244e+11
4,16308747029,2037374129,34903529762,263839496,5308705373,25492912808,7558082163,21278479393,23797814592,16078311792,1.530278e+11

**Ejemplo:** Generar un DataFrame eliminando todas las columnas de Demanda y dejando solo una columna DemandaAgregada con la suma de toda la demanda.

Sugerencia: para eliminar columnas usamos `.drop([LISTA de COLUMNAS], axis = 1)`

In [43]:
macroAgregada = macro.copy()
macroAgregada["DemandaAgregada"] =  macro[[col for col in macro.columns if 'Demanda' in col]].sum(axis = 1)
macroAgregada.head()

,ano,pbi,OfertaAgricultura,OfertaMinas,OfertaManufacturera,OfertaElectricidad,OfertaConstruccion,OfertaComercio,OfertaTransporte,OfertaFinaciera,...,DemandaConsumoGobiertano,DemandaConstrucciones,DemandaMaterialNacional,DemandaMaterialImportada,DemandaMaquinariaNacional,DemandaMaquinariaImportaciones,DemandaExportaciones,DemandaImportaciones,DemandaGib,DemandaAgregada
0,1950,142098481044,13696637358,1452011417,32304751942,198218385,5918090281,25281650565,7262970408,19550757718,...,21706316451,20353627362,668586865,584400198,3119383475,863112352,10729585056,14039465296,142098481044,318818537811
1,1951,147436076837,14629457210,1686941522,33149279696,212725994,6060937395,26260862055,7534071597,19902737804,...,21767097618,21739314091,842740200,2532757698,3562534310,1292775007,8455493993,15744444593,147436076837,333910951794
2,1952,140491256038,12545616104,1794762161,32522906863,227896262,5571363747,24417324287,7017131008,20598804008,...,21455589059,19685428171,1119084065,1484421674,3440750327,1088415946,6224082425,11637586183,140491256038,311734667569
3,1953,147324304004,16402296333,1925706862,32341045582,242404261,5546340195,24009746257,7210541490,20716225895,...,20742065172,20237375978,1207890913,1459988875,3621895632,886926720,9619869463,9626750804,147324304004,321129969182
4,1954,153315563451,16308747029,2037374129,34903529762,263839496,5308705373,25492912808,7558082163,21278479393,...,21238933697,19372130307,1173451578,805900196,4121320340,783079947,10201623290,12506287869,153315563451,337910687090

In [44]:
# Eliminamos las columnas
macroAgregada = macro.drop([col for col in macro.columns if 'Demanda' in col], axis = 1)

**Ejemplo:** Generar un DataFrame que contenga: año, pbi, OfertaSuma y DemandaSuma.

In [45]:
# Podemos usar concat para pegar columnas en un data frame (alinea los datos con mismo índice)
macroResumen = pd.concat([macro[["ano", "pbi"]],  
                          macro[[col for col in macro.columns if col.startswith("Oferta")]].sum(axis = 1),
                          macro[[col for col in macro.columns if col.startswith("Demanda")]].sum(axis = 1)], axis = 1)

macroResumen.head()

    ano           pbi             0             1
0  1950  142098481044  142106455656  318818537811
1  1951  147436076837  147200402832  333910951794
2  1952  140491256038  141921881231  311734667569
3  1953  147324304004  146724398146  321129969182
4  1954  153315563451  153027796537  337910687090

In [ ]:
# Ejercicio: ajustar el ejercicio anterior para que las columnas se llamen "OfertaAgregada" y "DemandaAgregada".

### C. Aplicar funciones distintas según alguna condición.

La función que usamos para listas por comprensión es una función lambda `(lambda x : f(x))`, pero solo ponemos f(x).

La funciones lambda permiten usar condiciones if de la siguiente forma para definir funciones partidas

`lambda x : f(x) if CONDICION else g(x)`

**Ejercicio:** Implementar la siguiente funcion como función lambda:
$$
 f(x)= 
\begin{cases}
x + 1 & \text{if } x \geq 2 \\
x^2   & \text{if } x < 2
\end{cases}
$$

In [47]:
f = lambda x : x+1 if x >= 2 else x**2
f(1)

1

**Ejemplo.** Queremos agregar "Super" adelante de todas las variables de Oferta.

Para listas por comprensión usamos la sintaxis

`[f(x) if CONDICION else g(x) for x in LISTA]`

Acá `f(x) if CONDICION else g(x)` es una función lambda.

In [ ]:
# Ejemplo. Qué hace el siguiente comando?
[x / 2 if (x % 2 == 0) else x for x in np.arange(1,10)]   # np.arange nos da todos los enteros desde 1 a 10 (exclusive)

**Nota:** Comparar con el if que habiamos usado antes en listas por comprensión, ¿cuál es la diferencia?

**Ejercicio.**
Convertir todos los nombres de columnas de Oferta a mayúsculas.

**Ejercicio:** Como podemos combinar los dos "if"? Generar una lista de nombres de columnas que no tenga las variables de demanda y a las de oferta le agregamos Super al principio.

**Ejercicio.** Por un error en el formato CSV, todos los nombres de columnas en el siguiente dataframe excepto "ano" tienen un espacio adelante. Generar un DataFrame macroClean con los nombres arreglados.
1. Realizarlo utilizando la función str.strip
2. Realizarlo utilizando c[1:] para eliminar el primer caracter en los casos que corresponda

In [ ]:
macroEspacio = pd.read_csv("OfertaYDemandaEspacio.csv")
macroEspacio.head()

In [ ]:
macroEspacio.columns